import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { config } from "../config.js";
import { productRepository } from "../db/repositories/product.repository.js";
import { NotFoundError, ValidationError } from "../domain/shared/errors.js";
import { auditService } from "./audit.service.js";

const PACKAGE_JSON_TEMPLATE = (name: string): string =>
  JSON.stringify(
    {
      name,
      version: "0.0.1",
      private: true,
      type: "module",
      description: "[DEV FIXTURE] Generated by the VentureForge SaaS Factory (docs/M6_ARCHITECTURE_PROPOSAL.md). A disposable demo workspace, never a real product.",
      dependencies: { express: "^4.21.0" },
    },
    null,
    2,
  ) + "\n";

const TSCONFIG_TEMPLATE = JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      lib: ["ES2022"],
      outDir: "dist",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
    },
    include: ["src/**/*.ts", "tests/**/*.ts"],
  },
  null,
  2,
) + "\n";

/**
 * Without its own vitest.config.ts, vitest's config resolution walks
 * UP from cwd exactly like Node's/TypeScript's module resolution does
 * (§10) — and would find VentureForge's OWN root vitest.config.ts,
 * whose globalSetup/setupFiles reference paths that only exist in
 * VentureForge's own tests/ directory. A minimal, explicit, workspace-
 * local config (no globalSetup, no setupFiles) is what keeps a
 * generated workspace's own `vitest run` genuinely isolated.
 */
const VITEST_CONFIG_TEMPLATE =
  `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    globals: false,
    include: ["tests/**/*.test.ts"],
  },
});
`;

const INDEX_TS_TEMPLATE =
  `// [DEV FIXTURE] Starter scaffold provisioned by the SaaS Factory (docs/M6_ARCHITECTURE_PROPOSAL.md §10).
// The Engineering Agent adds the product's own routes on top of this file — never presented as a real,
// deployed service.
import express, { type Express } from "express";

export function createApp(): Express {
  const app = express();
  app.use(express.json());
  app.get("/health", (_req, res) => res.json({ status: "ok" }));
  return app;
}
`;

const HEALTH_TEST_TS_TEMPLATE =
  `// [DEV FIXTURE] Provisioned by the SaaS Factory — proves the workspace's own toolchain (vitest, reused from
// VentureForge's own node_modules, docs/M6_ARCHITECTURE_PROPOSAL.md §10) actually runs real tests.
import { describe, expect, it } from "vitest";
import { createApp } from "../src/index.js";

describe("health", () => {
  it("GET /health returns ok", async () => {
    const app = createApp();
    const server = app.listen(0);
    const address = server.address();
    const port = typeof address === "object" && address ? address.port : 0;
    const res = await fetch(\`http://127.0.0.1:\${port}/health\`);
    const body = await res.json();
    expect(res.status).toBe(200);
    expect(body).toEqual({ status: "ok" });
    server.close();
  });
});
`;

/**
 * Provisions the disposable, gitignored on-disk workspace a Product's
 * engineering tasks will write into (docs/M6_ARCHITECTURE_PROPOSAL.md
 * §10) — plain filesystem writes, not a Guardian-gated tool call: this
 * is platform bootstrapping the orchestrator performs once per
 * Product, the same category of action as a demo script provisioning
 * its own disposable SQLite database directly via Node's fs, never an
 * agent "doing" something. Every subsequent write inside this
 * directory goes through write_workspace_file (Guardian-gated,
 * WRITE_WORKSPACE_FILES).
 */
export const workspaceService = {
  async provision(productId: string): Promise<string> {
    const product = await productRepository.findById(productId);
    if (!product) throw new NotFoundError("Product", productId);
    if (product.workspacePath) {
      throw new ValidationError(`Product ${productId} already has a workspace (${product.workspacePath}) — provisioning only ever happens once.`);
    }

    const workspacePath = join(config.factoryWorkspacesDir, productId);
    await mkdir(join(workspacePath, "src"), { recursive: true });
    await mkdir(join(workspacePath, "tests"), { recursive: true });
    await writeFile(join(workspacePath, "package.json"), PACKAGE_JSON_TEMPLATE(`factory-product-${productId}`));
    await writeFile(join(workspacePath, "tsconfig.json"), TSCONFIG_TEMPLATE);
    await writeFile(join(workspacePath, "vitest.config.ts"), VITEST_CONFIG_TEMPLATE);
    await writeFile(join(workspacePath, "src", "index.ts"), INDEX_TS_TEMPLATE);
    await writeFile(join(workspacePath, "tests", "health.test.ts"), HEALTH_TEST_TS_TEMPLATE);

    await productRepository.setWorkspacePath(productId, workspacePath);

    await auditService.record({
      actorType: "SYSTEM",
      actorId: null,
      action: "PROVISION_WORKSPACE",
      resourceType: "PRODUCT",
      resourceId: productId,
      result: "SUCCESS",
      metadata: { workspacePath },
    });

    return workspacePath;
  },
};
