-- The `events` table's CHECK constraint on `type` hardcodes the full
-- DOMAIN_EVENT_TYPES list (src/domain/events/event.types.ts) and must be
-- rebuilt every time a new domain event type is added — the same gap
-- M3, M4, M5, M6, M7, and M9 each already closed for their own new
-- event types (see e.g. 20260901120000_m3_event_types). This migration
-- adds exactly one new value, CUSTOMER_DISCOVERY_INTERACTION_RECORDED
-- (Customer Discovery + Validation layer), to the end of the existing
-- list — no other value is removed or reordered. No other table's
-- constraints are affected; `events` has no foreign keys in or out.
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_events" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "type" TEXT NOT NULL CHECK ("type" IN ('AGENT_CREATED', 'AGENT_SUSPENDED', 'TASK_CREATED', 'TASK_COMPLETED', 'TASK_FAILED', 'EVIDENCE_ADDED', 'OPPORTUNITY_DISCOVERED', 'OPPORTUNITY_SCORED', 'OPPORTUNITY_UPDATED', 'APPROVAL_REQUESTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'SIGNAL_CLUSTER_CREATED', 'PROBLEM_EXTRACTED', 'COMPETITOR_ANALYSIS_COMPLETED', 'RESEARCH_CYCLE_STARTED', 'RESEARCH_CYCLE_COMPLETED', 'OPPORTUNITY_DECISION_RECORDED', 'CLAIM_EXTRACTED', 'CLAIM_VALIDATED', 'CEO_RECOMMENDATION_ISSUED', 'INVESTMENT_MEMO_CREATED', 'OPPORTUNITY_KILLED', 'DECISION_CYCLE_STARTED', 'DECISION_CYCLE_COMPLETED', 'PROSPECT_DISCOVERED', 'OUTREACH_EXPERIMENT_APPROVED', 'OUTREACH_MESSAGE_DRAFTED', 'OUTREACH_MESSAGE_CONTACTED', 'CUSTOMER_RESPONSE_RECORDED', 'CUSTOMER_EVIDENCE_CREATED', 'CUSTOMER_DISCOVERY_MEMO_CREATED', 'PRODUCT_APPROVED', 'PRODUCT_SPEC_CREATED', 'MVP_ARCHITECTURE_CREATED', 'ENGINEERING_TASK_COMPLETED', 'SECURITY_REVIEW_COMPLETED', 'PRODUCT_REVIEW_MEMO_CREATED', 'PRODUCT_READY_FOR_DEPLOYMENT', 'PRODUCT_DEPLOYED', 'PRODUCT_ROLLED_BACK', 'BILLING_ACTIVATED', 'LAUNCH_REVIEW_MEMO_CREATED', 'INCIDENT_DETECTED', 'INCIDENT_RESOLVED', 'SUPPORT_CASE_CREATED', 'BUSINESS_REVIEW_MEMO_CREATED', 'GROWTH_EXPERIMENT_COMPLETED', 'ANOMALY_DETECTED', 'PORTFOLIO_ANALYZED', 'CUSTOMER_VALIDATED', 'PRODUCT_CREATED', 'REVENUE_OBSERVED', 'CHAIRMAN_REVIEW_COMPLETED', 'HUMAN_DECISION_MADE', 'ACTION_EXECUTED', 'OUTCOME_OBSERVED', 'LESSON_CREATED', 'OPERATING_CYCLE_STAGE_ADVANCED', 'ATTENTION_QUEUE_UPDATED', 'EMERGENCY_STOP_ACTIVATED', 'EMERGENCY_STOP_RESUMED', 'CUSTOMER_DISCOVERY_INTERACTION_RECORDED')),
    "payload" TEXT NOT NULL,
    "occurred_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "new_events" ("id", "type", "payload", "occurred_at") SELECT "id", "type", "payload", "occurred_at" FROM "events";
DROP TABLE "events";
ALTER TABLE "new_events" RENAME TO "events";
CREATE INDEX "events_type_idx" ON "events"("type");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
