/**
 * Constitution §22's own pipeline, stored: PREDICTION -> ACTUAL RESULT
 * -> ERROR -> ROOT CAUSE -> LESSON -> POLICY/MODEL/PROCESS UPDATE.
 * (docs/M8_ARCHITECTURE_PROPOSAL.md §38, M8 brief §41.) A record is
 * generated by a deterministic threshold check on a resolved
 * PredictionOutcome's error, never by an agent free-associating a
 * lesson. `suggestedProcessChange` is free text a human reads — no
 * code path in this codebase ever reads a LearningRecord and edits a
 * system prompt, a permission, a risk level, or a formula constant
 * (that would require the existing governance process and explicit
 * human action, and this milestone builds no such path at all).
 */
export const LEARNING_RECORD_ERROR_THRESHOLD = 0.25;

export function shouldGenerateLearningRecord(errorPct: number | null): boolean {
  return errorPct !== null && Math.abs(errorPct) > LEARNING_RECORD_ERROR_THRESHOLD;
}

/**
 * M9 — docs/M9_ARCHITECTURE_PROPOSAL.md §30, M9 brief §18's own list,
 * verbatim. Constrains LearningRecord.rootCause's existing free-text
 * column with a documented, closed vocabulary — additive, no schema
 * change (rootCause was already a nullable String).
 */
export const LEARNING_ROOT_CAUSES = [
  "BAD_EVIDENCE",
  "INSUFFICIENT_EVIDENCE",
  "BAD_ASSUMPTION",
  "BAD_MODEL_REASONING",
  "WRONG_MARKET",
  "EXECUTION_FAILURE",
  "EXTERNAL_SHOCK",
  "MEASUREMENT_ERROR",
] as const;
export type LearningRootCause = (typeof LEARNING_ROOT_CAUSES)[number];

export function isLearningRootCause(value: string): value is LearningRootCause {
  return (LEARNING_ROOT_CAUSES as readonly string[]).includes(value);
}
