/**
 * Constitution §22's own pipeline, stored: PREDICTION -> ACTUAL RESULT
 * -> ERROR -> ROOT CAUSE -> LESSON -> POLICY/MODEL/PROCESS UPDATE.
 * (docs/M8_ARCHITECTURE_PROPOSAL.md §38, M8 brief §41.) A record is
 * generated by a deterministic threshold check on a resolved
 * PredictionOutcome's error, never by an agent free-associating a
 * lesson. `suggestedProcessChange` is free text a human reads — no
 * code path in this codebase ever reads a LearningRecord and edits a
 * system prompt, a permission, a risk level, or a formula constant
 * (that would require the existing governance process and explicit
 * human action, and this milestone builds no such path at all).
 */
export const LEARNING_RECORD_ERROR_THRESHOLD = 0.25;

export function shouldGenerateLearningRecord(errorPct: number | null): boolean {
  return errorPct !== null && Math.abs(errorPct) > LEARNING_RECORD_ERROR_THRESHOLD;
}
